### ISSUE TITLE
Not working fine on macOS

### ISSUE THREAD

**Issue by 50U10FCA7** [dtolnay/inventory#52]
Inventory stops collecting anything on MacOS in some cases. Think it's because of fn pointers inside plugin, but not sure.

Here's MRE (see GitHub actions):
https://github.com/50U10FCA7/inventory_issue_test

**Comment by trevyn** [comment]
This works for me with:

```toml
[profile.dev]
incremental = false

[profile.release]
codegen-units = 1
```
